"""
Django settings for django1 project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django.urls.base import reverse_lazy
#reverse_laze와 reverse
#공통점
# - 등록된 URL의 별칭을 바탕으로 URL을 반환하는 함수
#차이점 - url을 반환하는 시기
# - reverse : 함수호출이 되자마자 등록된 URL에서 찾음
# - reverse_lazy : 웹 서버가 정삭적으로 실행이 된 뒤에 등록된 url에서 찾음

# 헷갈리는 경우 모두 reverse_lazy를 써도 무방함


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#login_required 데코레이터가 띄우는 로그인 URL을 설정
LOGIN_URL = reverse_lazy('cl:signin')
#소셜 로그인 완료 후 이동할URL주소를 저장하는 변수-django 기능
LOGIN_REDIRECT_URL = reverse_lazy('blog:index')

#social_django 어플리케이션 설정 값

#인증관련 모듈을 추가'    
AUTHENTICATION_BACKENDS = ( 
    #구글 로그인 처리관련 파이썬 클래스 추가
    'social_core.backends.open_id.OpenIdAuth',
    'social_core.backends.google.GoogleOpenId',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GooglePlusAuth',
    #소셜 로그인 정보를 django의 user모델 클래스에 저장하기 위한 클래스
    'django.contrib.auth.backends.ModelBackend',
    )

#구글 개발자 사이트에서 발급 받은 ID PASSWORD저장
SOCIAL_AUTH_GOOGLE_PLUS_KEY = '5726939963-rdp8ggtr0qav7tl3akgn9pirls1bpaak.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_PLUS_SECRET = 'PrvCsrY3eV5097QLqjajExMB'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's5)%c$9dxzsekf)b(etus^6mzs#&r@mq$07iy3@w%7_u5ala38'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
#프로젝트 내에서 실행할 어플리케이션을 등록//관리하는 변수
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookmark', #웹프로젝트에 book mark 어플리케션이 존재한는 것을 등록
    'vote',
    'customlogin',
    'blog',
    #pip install social-auth-app-django 명령어로 설치해야만 사용할 수 있다 
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #소셜 로그인 처리를 위한 템플릿관련함수 추가
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'django1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

#클라이언트의 요청으로 저장하는 미디어파일(이미지, 첨부파일) 설정
#MEDIA_URL : URL주소로 파일 주소를 접근할 때 사용하는 URL을 저장하는 변수

#127.0.0.1:8000/files/로 시작하는 경로는 미디어 파일을 불러오는 것으로 판단 함
MEDIA_URL = '/files/'
#MEDIA_ROOT : 실제로 파일이 저장되는 하드웨어 경로
#BASE_DIR : 웹프로젝트가 저장된 경로
#os.path.join(기존 경로, 새 경로) :기존 경로에 새 경로를 붙인 문자열을 생성

#현재 프로젝트 폴더/files에 클라이 언트가 업로드한 파일이 저장되도록 설정
MEDIA_ROOT = os.path.join(BASE_DIR, 'files')
#C;/files/폴더에 미디어 파일이 저장되도록 설정
#MEDIA_ROOT = 'c:/files'
#MEDIA_URL, MEDIA_ROOT를 설정한 뒤, 메인 URLConf에서 URL과 하드웨어 경로를 매칭하는 작업을 수행해야함